import {
	Loader,
	Mail,
	Sun,
	MoonStar,
	Plus,
	PanelLeft,
	ChevronsUpDown,
	BadgeCheck,
	BadgeX,
	LogOut,
	Trash,
	User,
	Ellipsis,
	PinOff,
	Pin,
	ExternalLink,
	Share,
	ChevronUp,
	ChevronDown,
	X,
	Cloud,
	Info,
	Square,
	SquareCheck,
	Archive,
	ScanEye,
	PlusCircle,
	ChevronsDown,
	ChevronsUp,
	Pencil,
	ArrowLeftRight,
	ArrowUpDown,
	CalendarDays
} from '@lucide/svelte/icons';
import Google from './google.svelte';
import Github from './github.svelte';

const Icons = {
	email: Mail,
	google: Google,
	github: Github,
	loader: Loader,
	sun: Sun,
	moon: MoonStar,
	add: Plus,
	sidebar: PanelLeft,
	chevronsUpDown: ChevronsUpDown,
	badgeCheck: BadgeCheck,
	badgeX: BadgeX,
	logOut: LogOut,
	trash: Trash,
	person: User,
	ellipsis: Ellipsis,
	pinOff: PinOff,
	pin: Pin,
	externalLink: ExternalLink,
	share: Share,
	chevronUp: ChevronUp,
	chevronDown: ChevronDown,
	clear: X,
	cloud: Cloud,
	info: Info,
	active: Square,
	completed: SquareCheck,
	archive: Archive,
	review: ScanEye,
	addCircle: PlusCircle,
	low: ChevronsDown,
	medium: ChevronsUpDown,
	high: ChevronsUp,
	edit: Pencil,
	arrowLeftRight: ArrowLeftRight,
	arrowUpDown: ArrowUpDown,
	calendar: CalendarDays
};

export default Icons;
